//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4984
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 炸弹人.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("炸弹人.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon Main {
            get {
                object obj = ResourceManager.GetObject("Main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 墙体_出口 {
            get {
                object obj = ResourceManager.GetObject("墙体_出口", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 墙体_墙 {
            get {
                object obj = ResourceManager.GetObject("墙体_墙", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 墙体_砖块 {
            get {
                object obj = ResourceManager.GetObject("墙体_砖块", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_上_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_上_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_上_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_上_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上下_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_上下_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上下_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_上下_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上下_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_上下_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_上下_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_上下_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_下_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_下_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_下_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_下_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_下_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_下_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_下_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_下_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_中_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_中_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_中_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_中_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_中_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_中_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_中_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_中_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_右_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_右_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_右_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_右_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_右_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_右_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_右_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_右_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_左_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_左_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_左_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_左_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左右_1 {
            get {
                object obj = ResourceManager.GetObject("火焰_左右_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左右_2 {
            get {
                object obj = ResourceManager.GetObject("火焰_左右_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左右_3 {
            get {
                object obj = ResourceManager.GetObject("火焰_左右_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 火焰_左右_4 {
            get {
                object obj = ResourceManager.GetObject("火焰_左右_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 炸弹_1 {
            get {
                object obj = ResourceManager.GetObject("炸弹_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 炸弹_2 {
            get {
                object obj = ResourceManager.GetObject("炸弹_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 炸弹_3 {
            get {
                object obj = ResourceManager.GetObject("炸弹_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_火焰 {
            get {
                object obj = ResourceManager.GetObject("物品_火焰", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_炸弹 {
            get {
                object obj = ResourceManager.GetObject("物品_炸弹", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_穿墙 {
            get {
                object obj = ResourceManager.GetObject("物品_穿墙", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_穿炸弹 {
            get {
                object obj = ResourceManager.GetObject("物品_穿炸弹", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_遥控炸弹 {
            get {
                object obj = ResourceManager.GetObject("物品_遥控炸弹", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 物品_鞋子 {
            get {
                object obj = ResourceManager.GetObject("物品_鞋子", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 玩家1 {
            get {
                object obj = ResourceManager.GetObject("玩家1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_上_1 {
            get {
                object obj = ResourceManager.GetObject("玩家1_上_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_上_2 {
            get {
                object obj = ResourceManager.GetObject("玩家1_上_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_上_3 {
            get {
                object obj = ResourceManager.GetObject("玩家1_上_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_下_1 {
            get {
                object obj = ResourceManager.GetObject("玩家1_下_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_下_2 {
            get {
                object obj = ResourceManager.GetObject("玩家1_下_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_下_3 {
            get {
                object obj = ResourceManager.GetObject("玩家1_下_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_右_1 {
            get {
                object obj = ResourceManager.GetObject("玩家1_右_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_右_2 {
            get {
                object obj = ResourceManager.GetObject("玩家1_右_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_右_3 {
            get {
                object obj = ResourceManager.GetObject("玩家1_右_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_左_1 {
            get {
                object obj = ResourceManager.GetObject("玩家1_左_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_左_2 {
            get {
                object obj = ResourceManager.GetObject("玩家1_左_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_左_3 {
            get {
                object obj = ResourceManager.GetObject("玩家1_左_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_1 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_2 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_3 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_4 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_5 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家1_死亡_6 {
            get {
                object obj = ResourceManager.GetObject("玩家1_死亡_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap 玩家2 {
            get {
                object obj = ResourceManager.GetObject("玩家2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_上_1 {
            get {
                object obj = ResourceManager.GetObject("玩家2_上_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_上_2 {
            get {
                object obj = ResourceManager.GetObject("玩家2_上_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_上_3 {
            get {
                object obj = ResourceManager.GetObject("玩家2_上_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_下_1 {
            get {
                object obj = ResourceManager.GetObject("玩家2_下_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_下_2 {
            get {
                object obj = ResourceManager.GetObject("玩家2_下_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_下_3 {
            get {
                object obj = ResourceManager.GetObject("玩家2_下_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_右_1 {
            get {
                object obj = ResourceManager.GetObject("玩家2_右_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_右_2 {
            get {
                object obj = ResourceManager.GetObject("玩家2_右_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_右_3 {
            get {
                object obj = ResourceManager.GetObject("玩家2_右_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_左_1 {
            get {
                object obj = ResourceManager.GetObject("玩家2_左_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_左_2 {
            get {
                object obj = ResourceManager.GetObject("玩家2_左_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_左_3 {
            get {
                object obj = ResourceManager.GetObject("玩家2_左_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_1 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_2 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_3 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_4 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_5 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 玩家2_死亡_6 {
            get {
                object obj = ResourceManager.GetObject("玩家2_死亡_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_1 {
            get {
                object obj = ResourceManager.GetObject("砖块_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_2 {
            get {
                object obj = ResourceManager.GetObject("砖块_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_3 {
            get {
                object obj = ResourceManager.GetObject("砖块_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_4 {
            get {
                object obj = ResourceManager.GetObject("砖块_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_5 {
            get {
                object obj = ResourceManager.GetObject("砖块_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon 砖块_6 {
            get {
                object obj = ResourceManager.GetObject("砖块_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
